---
- hosts: all
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443

  tasks:
    - name: add adom {{adom}}
      fmgr_generic:
        method: add
        params:
          - url: '/dvmdb/adom'
            data:
              - name: '{{adom}}'
                os_ver: '6.0'
                mr: 4
    - name: create address object
      fmgr_generic:
        method: add
        params:
          - data:
              - name: 'AnsibleAddress'
                subnet: '10.10.1.15 255.255.255.255'
            url: '/pm/config/adom/{{adom}}/obj/firewall/address'
#      ignore_errors: yes

#   - name: Create a script on FortiManager.
#     fmgr_dvmdb_script:
#       adom: 'adom'
#       state: 'present'
#       dvmdb_script:
#         desc: 'The script create via Ansible'
#         type: 'cli'
#         name: 'fooscript'
#         content: |
#                        config system global
#                           set timezone 04
#                        end
