# - name: 'Create adom'
#   hosts:  all
#   gather_facts: no
#   connection: httpapi
#   collections:
#     - fortinet.fortimanager
#   vars:
#     # geo_zone: 'NA'
#     # adom: 'AnsibleTest'
#     # fsw: 'FSW108E'
#     # fsw_nm: '{{fsw}}'
#     # fsw_tpt: '{{fsw}}'
#     # fap: 'FAP24D'
#     # fap_prof: 'AP-P'
#     # sdwan: 'SDWan'
#     # sdwan_tpt: '{{sdwan}}_template'
#     # ipsec_tpt: 'IPsec_template'
#     # ipsec_tun: 'ipsec_tun'
#     # fex: 'FXT40D'
#     # pos_subnet: '192.168.100'
#     # securewlan_subnet: '192.168.110'
#     # backoffice_subnet: '192.168.120'
#     # iot_subnet: '192.168.130'
#     # guestwlan_subnet: '192.168.200'
#     # address: Sugarloaf, FL
#     # script_adom: 'prep_adom'
#     # polpkg: 'PP_{{geo_zone}}'
#     ansible_httpapi_use_ssl: true
#     ansible_httpapi_validate_certs: false
#     adom: 'AnsibleTest'
#     fgt:  'FGT40F'

#   tasks:

#     - name: add adom {{adom}}
#       fmgr_generic:
#         method: add
#         params:
#           - url: '/dvmdb/adom'
#             data:
#               - name: '{{adom}}'
#                 flags: [ central_sdwan, no_vpn_console ] # no_vpn_console, 
#                 os_ver: '6.0'
#                 mr: 2
---
- hosts: fortimanagers
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443

  tasks:
   #  - name: add adom 
   #    fmgr_generic:
   #      method: add
   #      params:
   #        - url: '/dvmdb/adom'
   #          data:
   #            - name: adom
   #              os_ver: '6.0'
   #              mr: 4
    -   name: 'login a user'
        fmgr_generic:
             method: 'exec'
             params:
                - url: 'sys/login/user'
                  data:
                   - user: 'json'
                     passwd: '123456'
#      ignore_errors: yes

#   - name: Create a script on FortiManager.
#     fmgr_dvmdb_script:
#       adom: 'adom'
#       state: 'present'
#       dvmdb_script:
#         desc: 'The script create via Ansible'
#         type: 'cli'
#         name: 'fooscript'
#         content: |
#                        config system global
#                           set timezone 04
#                        end
