---
all:
  hosts:
    teddy:
      ansible_host: 172.31.200.57
      ansible_user: 'json'
      ansible_password: '123456'
    tsvetan:
      ansible_host:
      ansible_user:
      ansible_password:
  vars:
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_become: no
    ansible_become_method: disable
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    # project
    adom: 'AnsibleTest'
    fgt:  'FGT40F'